# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/CreateIndividualPage.qml) \
        $$quote($$BASEDIR/assets/CreateQuotePage.qml) \
        $$quote($$BASEDIR/assets/CreateTafsirPage.qml) \
        $$quote($$BASEDIR/assets/Dashboard.qml) \
        $$quote($$BASEDIR/assets/IndividualPickerPage.qml) \
        $$quote($$BASEDIR/assets/IndividualTextField.qml) \
        $$quote($$BASEDIR/assets/IndividualsPane.qml) \
        $$quote($$BASEDIR/assets/LocationPickerPage.qml) \
        $$quote($$BASEDIR/assets/QuotesPane.qml) \
        $$quote($$BASEDIR/assets/SettingsPage.qml) \
        $$quote($$BASEDIR/assets/TafsirAyats.qml) \
        $$quote($$BASEDIR/assets/TafsirContentsPage.qml) \
        $$quote($$BASEDIR/assets/TafsirPane.qml) \
        $$quote($$BASEDIR/assets/TafsirPickerPage.qml) \
        $$quote($$BASEDIR/assets/images/dropdown/ic_accept_new_suite.png) \
        $$quote($$BASEDIR/assets/images/dropdown/ic_save_individual.png) \
        $$quote($$BASEDIR/assets/images/dropdown/save_bio.png) \
        $$quote($$BASEDIR/assets/images/dropdown/save_quote.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_author.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_body.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_quote_body.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_quote_reference.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_reference.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_title.png) \
        $$quote($$BASEDIR/assets/images/dropdown/search_translator.png) \
        $$quote($$BASEDIR/assets/images/dropdown/suite_changes_accept.png) \
        $$quote($$BASEDIR/assets/images/dropdown/suite_changes_cancel.png) \
        $$quote($$BASEDIR/assets/images/list/ic_bio.png) \
        $$quote($$BASEDIR/assets/images/list/ic_companion.png) \
        $$quote($$BASEDIR/assets/images/list/ic_dislike.png) \
        $$quote($$BASEDIR/assets/images/list/ic_email.png) \
        $$quote($$BASEDIR/assets/images/list/ic_geo_result.png) \
        $$quote($$BASEDIR/assets/images/list/ic_geo_search.png) \
        $$quote($$BASEDIR/assets/images/list/ic_hidden.png) \
        $$quote($$BASEDIR/assets/images/list/ic_individual.png) \
        $$quote($$BASEDIR/assets/images/list/ic_like.png) \
        $$quote($$BASEDIR/assets/images/list/ic_location.png) \
        $$quote($$BASEDIR/assets/images/list/ic_phone.png) \
        $$quote($$BASEDIR/assets/images/list/ic_quote.png) \
        $$quote($$BASEDIR/assets/images/list/ic_tafsir.png) \
        $$quote($$BASEDIR/assets/images/list/ic_tafsir_ayat.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_bio.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_email.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_location.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_phone.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_quote.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_rijaal.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_search.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_site.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_student.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_suite.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_suite_page.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_add_teacher.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_bottom.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_capture_ayats.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_copy.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_delete_individual.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_delete_quote.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_delete_suite_page.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_edit_bio.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_edit_location.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_edit_quote.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_edit_rijaal.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_edit_suite.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_edit_suite_page.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_link_ayat_to_tafsir.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_preview.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_bio.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_companions.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_email.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_location.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_phone.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_site.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_student.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_suite.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_remove_teacher.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_replace_individual.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_search.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_search_action.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_search_individual.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_search_location.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_select_individuals.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_set_companions.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_set_marker.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_settings.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_top.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_unlink_tafsir_ayat.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_update_link.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_upload_local.png) \
        $$quote($$BASEDIR/assets/images/menu/ic_validate_location.png) \
        $$quote($$BASEDIR/assets/images/menu/transfer_error.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_bios.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_individuals.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_locations.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_quotes.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_suite_ayats.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_suite_pages.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_suites.png) \
        $$quote($$BASEDIR/assets/images/placeholders/empty_tafsir.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_bios.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_individuals.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_quotes.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_suite_ayats.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_suite_pages.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_suites.png) \
        $$quote($$BASEDIR/assets/images/progress/loading_surah.png) \
        $$quote($$BASEDIR/assets/images/progress/uploading_local.png) \
        $$quote($$BASEDIR/assets/images/tabs/ic_bio.png) \
        $$quote($$BASEDIR/assets/images/tabs/ic_dash.png) \
        $$quote($$BASEDIR/assets/images/tabs/ic_quotes.png) \
        $$quote($$BASEDIR/assets/images/tabs/ic_rijaal.png) \
        $$quote($$BASEDIR/assets/images/tabs/ic_tafsir.png) \
        $$quote($$BASEDIR/assets/images/toast/ic_duplicate_replace.png) \
        $$quote($$BASEDIR/assets/images/toast/ic_location_added.png) \
        $$quote($$BASEDIR/assets/images/toast/ic_no_ayat_found.png) \
        $$quote($$BASEDIR/assets/images/toast/ic_no_shared_folder.png) \
        $$quote($$BASEDIR/assets/images/toast/ic_offline.png) \
        $$quote($$BASEDIR/assets/images/toast/incomplete_field.png) \
        $$quote($$BASEDIR/assets/images/toast/invalid_entry.png) \
        $$quote($$BASEDIR/assets/images/toast/no_geo_found.png) \
        $$quote($$BASEDIR/assets/images/toast/permission_toast_bg.amd) \
        $$quote($$BASEDIR/assets/images/toast/permission_toast_bg.png) \
        $$quote($$BASEDIR/assets/images/toast/success_upload_local.png) \
        $$quote($$BASEDIR/assets/images/toast/toast_bg.amd) \
        $$quote($$BASEDIR/assets/images/toast/toast_bg.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/xml/quran-data.xml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/CommonConstants.cpp) \
        $$quote($$BASEDIR/src/IlmHelper.cpp) \
        $$quote($$BASEDIR/src/InvokeHelper.cpp) \
        $$quote($$BASEDIR/src/QuranHelper.cpp) \
        $$quote($$BASEDIR/src/ThreadUtils.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/CommonConstants.h) \
        $$quote($$BASEDIR/src/IlmHelper.h) \
        $$quote($$BASEDIR/src/InvokeHelper.h) \
        $$quote($$BASEDIR/src/QueryId.h) \
        $$quote($$BASEDIR/src/QuranHelper.h) \
        $$quote($$BASEDIR/src/ThreadUtils.h) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/dropdown/*.qml) \
        $$quote($$BASEDIR/../assets/images/dropdown/*.js) \
        $$quote($$BASEDIR/../assets/images/dropdown/*.qs) \
        $$quote($$BASEDIR/../assets/images/list/*.qml) \
        $$quote($$BASEDIR/../assets/images/list/*.js) \
        $$quote($$BASEDIR/../assets/images/list/*.qs) \
        $$quote($$BASEDIR/../assets/images/menu/*.qml) \
        $$quote($$BASEDIR/../assets/images/menu/*.js) \
        $$quote($$BASEDIR/../assets/images/menu/*.qs) \
        $$quote($$BASEDIR/../assets/images/placeholders/*.qml) \
        $$quote($$BASEDIR/../assets/images/placeholders/*.js) \
        $$quote($$BASEDIR/../assets/images/placeholders/*.qs) \
        $$quote($$BASEDIR/../assets/images/progress/*.qml) \
        $$quote($$BASEDIR/../assets/images/progress/*.js) \
        $$quote($$BASEDIR/../assets/images/progress/*.qs) \
        $$quote($$BASEDIR/../assets/images/tabs/*.qml) \
        $$quote($$BASEDIR/../assets/images/tabs/*.js) \
        $$quote($$BASEDIR/../assets/images/tabs/*.qs) \
        $$quote($$BASEDIR/../assets/images/toast/*.qml) \
        $$quote($$BASEDIR/../assets/images/toast/*.js) \
        $$quote($$BASEDIR/../assets/images/toast/*.qs) \
        $$quote($$BASEDIR/../assets/xml/*.qml) \
        $$quote($$BASEDIR/../assets/xml/*.js) \
        $$quote($$BASEDIR/../assets/xml/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
